### ISSUE TITLE
Error getting auctions

### ISSUE THREAD

**Issue by aiexz** [Obsidion-dev/asyncpixel#6]
**Describe the bug**
Error getting auctions by uuid

**To Reproduce**
Run this code and you can check that `auctions` returns blank array
```
client = asyncpixel.Client("API-KEY")
data = await client.get_key_data()
uuid = data.owner
auctions = await client.get_auction_from_player(uuid)
```

**Expected behavior**
Return array with items on auction 

**Screenshots**
No

**OS (please complete the following information:**
 - OS: Ubuntu 18.04, but it can be reproduced anywhere 
 - Python version 3.8.3 and 3.7.7
 - Version Latest

**Additional context**
Somehow, if I remove dash symbols from `uuid` variable then it works fine. So my solution is just to use `.replace('-', '')`

**Comment by Darkflame72** [comment]
This is due to the way hypixel deals with uuid's. It returns them in long format `405dcf08-b80f-4e23-b97d-943ad93d14fd` but it wishes for them to be searched in short format without the dashes `405dcf08b80f4e23b97d943ad93d14fd `. I will look at adding a function to cleanup the input so you can use both.

**Comment by Darkflame72** [comment]
As of the latest release this has been fixed.
