### ISSUE TITLE
Change in Hypixel API

### ISSUE THREAD

**Issue by aiexz** [Obsidion-dev/asyncpixel#77]
**Describe the bug**
Hypixel API has updated

**To Reproduce**
get any skyblock profile using api

**Expected behavior**
https://github.com/Obsidion-dev/asyncpixel/blob/master/tests/test_profile.py#L12

**Screenshots**
New response sample
https://hastebin.com/ayiluxoqip.json

**Comment by Darkflame72** [comment]
Due to Hypixel changing the api whenever they feel like and not documenting the profiles endpoint, it also changes based on player profile settings the model which we use is the only data which we know will be in it. I will add a raw point to the data so you can interface with the raw json response but I cannot add it all to the endpoint as it is not documented or stable on hypixels end.
